language: node_js

node_js:
  - "9"
  - "10"
  - "11"

script:
  - npm run lint
  - npm test

after_success:
  - npm run coverage

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
